---
title: "Batch correction across tissues and patients"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/Reports/Full_data_batch_correction.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in the data

```{r libraries, message=FALSE}
library(scran)
library(scater)
library(DropletUtils)
library(openxlsx)
library(Rtsne)
source("../Analysis/Functions/auxiliary.R")
```

# Batch correction across tissues

```{r batch-correction}
sce.list <- readRDS("../../../Dropbox (Cambridge University)/Oesophagus_single_cell/High_quality_sce.rds")

sce.list <- lapply(sce.list, function(n){
    rowData(n) <- rowData(n)[,1:3]
    n
  })

# Order sce objects for batch correction
order.names <- c("Patient2_SIGAD9_GOJ", "Patient8_SIGAE7_GOJ", "Patient10_SIGAB5_GOJ",
                 "Patient3_SIGAB5_SCJ", "Patient7_SIGAB4_SCJ", "Patient9_SIGAE9_SCJ",
                 "Patient10_SIGAA5_NE", "Patient2_SIGAC9_NE", "Patient7_SIGAA4_NE",
                 "Patient8_SIGAD7_NE", "Patient2_SIGAE9_GC", "Patient3_SIGAD5_GC",
                 "Patient7_SIGAD4_GC", "Patient12_SIGAD3_GC", "Patient3_SIGAC5_BE",
                 "Patient7_SIGAC4_BE", "Patient9_SIGAF9_BE", "Patient12_SIGAC3_BE",
                 "Patient7_SIGAE4_D2", "Patient8_SIGAG7_D2", "Patient9_SIGAH9_D2",
                 "Patient12_SIGAE3_D2", "Patient10_SIGAD5_SMG", "Patient11_SIGAA4_SMG",
                 "Patient13_SIGAC8_SMG", "Patient13_SIGAD8_GOJ", "Patient13_SIGAE8_GC")

sce.list <- sce.list[order.names]

# Combine sce objects
sce <- do.call("cbind", sce.list)
sce <- normalize(sce)
  
# Batch correction
corrected <- batch.correction(sce.list)
  
# Save batch corrected counts in metdata
metadata(sce)$corrected <- corrected
  
# Compute tsne on corrected counts
set.seed(1234)
tsne <- Rtsne(t(corrected), pca = FALSE)
  
# Store tsne in slot
reducedDims(sce)$TSNE <- tsne$Y[,1:2]

# Clustering on corrected data
g <- buildSNNGraph(corrected, k = 10)
clusters <- igraph::cluster_louvain(g)$membership

# Visualize clustering
ggplot(data.frame(tSNE1 = tsne$Y[,1],
                  tSNE2 = tsne$Y[,2],
                  clusters = as.factor(clusters))) + 
  geom_point(aes(tSNE1, tSNE2, colour = clusters))

# Tissue
ggplot(data.frame(tSNE1 = tsne$Y[,1],
                  tSNE2 = tsne$Y[,2],
                  clusters = as.factor(colData(sce)$Tissue))) + geom_point(aes(tSNE1, tSNE2, colour = clusters))

# Patient
ggplot(data.frame(tSNE1 = tsne$Y[,1],
                  tSNE2 = tsne$Y[,2],
                  clusters = as.factor(colData(sce)$Patient))) + geom_point(aes(tSNE1, tSNE2, colour = clusters))
  
# Save clustering in new slot
colData(sce)$Global_cluster <- clusters
  
# Perform differential expression
des <- model.matrix(~colData(sce)$Patient+colData(sce)$Tissue)
markers <- findMarkers(sce, clusters = colData(sce)$Global_cluster, design = des)
  
markers.spec <- lapply(markers, function(n){
  if(!is.na(n$Top[1])){
  cur_n <- n[n$FDR < 0.1 & apply(n[,3:ncol(n)], 1, function(x){sum(x > 0)}) == ncol(n) - 2,]
    if(nrow(cur_n) > 0){
      cur_n$GeneName <- rowData(sce)$Symbol[match(rownames(cur_n), rowData(sce)$ID)]
    }
  }
  else{
    cur_n <- NULL
  }
  cur_n
})
  
write.xlsx(markers.spec, paste("../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/Marker_genes/Global/Marker_genes.xlsx", sep = ""))

saveRDS(sce, "../../../Dropbox (Cambridge University)/Oesophagus_single_cell/All_corrected_sce.rds")
```

# Add tissue clutsering to batch corrected data

```{r}
all_sce <- readRDS("../../../Dropbox (Cambridge University)/Oesophagus_single_cell/All_corrected_sce.rds")
tissue_sce <- readRDS("../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Tissue_sce.rds")

tissue.clusters <- vector(length = ncol(all_sce))
names(tissue.clusters) <- paste(colData(all_sce)$Barcode, 
                                colData(all_sce)$Patient,
                                colData(all_sce)$Tissue, sep = "_")

for(i in 1:length(tissue_sce)){
  tissue.clusters[paste(colData(tissue_sce[[i]])$Barcode, 
                                colData(tissue_sce[[i]])$Patient,
                                colData(tissue_sce[[i]])$Tissue, sep = "_")] <- colData(tissue_sce[[i]])$Tissue_cluster
}

colData(all_sce)$Tissue_cluster <- tissue.clusters

saveRDS(all_sce, "../../../Dropbox (Cambridge University)/Oesophagus_single_cell/All_corrected_sce.rds")
```

