---
title: "Normalization"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/Reports/Normalization.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in the data

```{r libraries, message=FALSE}
library(scran)
library(scater)
library(openxlsx)
source("../Analysis/Functions/auxiliary.R")
```

Here, we compute tSNEs, perform clustering and detect marker genes

```{r data, eval=FALSE}
sce.list <- readRDS("../../../Dropbox (Cambridge University)/Oesophagus_single_cell/All_sce.rds")

for(i in 1:length(sce.list)){
  cur_sce <- sce.list[[i]]

  # tSNE
  if(!("TSNE" %in% reducedDimNames(cur_sce))){
    set.seed(1234)
    cur_sce <- runTSNE(cur_sce)
  }
  
  # Clustering
  if(!("Clusters" %in% names(colData(cur_sce)))){
    HVgenes <- HVG(cur_sce)
    cluster <- DTC(cur_sce, HVgenes)
    colData(cur_sce)$Clusters <- cluster
  }

  # Marker genes
  markers <- marker.detection(cur_sce, clusters = cluster)
  write.xlsx(markers, paste("../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/Marker_genes/Single_sample/", 
                            names(sce.list)[i], "/Marker_genes.xlsx", sep = ""))

  sce.list[[i]] <- cur_sce
}

saveRDS(sce.list, "../../../Dropbox (Cambridge University)/Oesophagus_single_cell/All_sce.rds")
```

# Removing lower quality libraries

For further downstream analysis, we exclude lower quality samples.

```{r exclude-samples}
QC <- read.xlsx("../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Additional_files/Library_quality.xlsx")
sce.good <- sce.list[QC$names[QC$good_quality == "yes"]]

saveRDS(sce.good, "../../../Dropbox (Cambridge University)/Oesophagus_single_cell/High_quality_sce.rds")
```

