---
title: "Batch correction across tissues"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/Reports/Tissue_correction.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in the data

```{r libraries, message=FALSE}
library(scran)
library(scater)
library(ggplot2)
library(DropletUtils)
library(openxlsx)
library(Rtsne)
source("../Analysis/Functions/auxiliary.R")
```

# Batch correction across tissues

```{r batch-correction}
sce.list <- readRDS("../../../Dropbox (Cambridge University)/Oesophagus_single_cell/High_quality_sce.rds")
tissue.list <- list()

for(i in c("NE", "GC", "BE", "GOJ", "SCJ", "D2", "SMG")){
  cur_sces <- sce.list[which(grepl(i, names(sce.list)))]
  cur_sces <- lapply(cur_sces, function(n){
    rowData(n) <- rowData(n)[,1:3]
    n
  })
  
  # Order sce object by size
  cur_sces <- cur_sces[order(unlist(lapply(cur_sces, ncol)), decreasing = TRUE)]
  
  # Combine sce objects
  tissue_sce <- do.call("cbind", cur_sces)
  tissue_sce <- normalize(tissue_sce)
  
  # Batch correction
  corrected <- batch.correction(cur_sces)
  
  # Save batch corrected counts in metdata
  metadata(tissue_sce)$corrected <- corrected
  
  # Compute tsne on corrected counts
  set.seed(1234)
  tsne <- Rtsne(t(corrected), pca = FALSE)
  
  # Store tsne in slot
  reducedDims(tissue_sce)$TSNE <- tsne$Y[,1:2]

  # Clustering on corrected data
  #dist.all <- as.dist(sqrt((1 - cor(as.matrix(corrected), 
  #                                    method = "spearman"))/2))
  #dendro <- hclust(dist.all, method = "ward.D2")
  #cluster <- as.character(cutreeDynamic(dendro = dendro, distM = as.matrix(dist.all), 
  #                      minClusterSize = 10, deepSplit = 0))
  g <- buildSNNGraph(corrected, k = 10)
  cluster <- igraph::cluster_louvain(g)$membership
  
  # Save clustering in new slot
  colData(tissue_sce)$Tissue_cluster <- cluster
  
  # Visualize whether populations are patient specific 
  table(cluster, colData(tissue_sce)$Patient)
  
  # Perform differential expression
  des <- model.matrix(~colData(tissue_sce)$Patient)
  markers <- findMarkers(tissue_sce, clusters = cluster, design = des)
  
  markers.spec <- lapply(markers, function(n){
    if(!is.na(n$Top[1])){
    cur_n <- n[n$FDR < 0.1 & apply(n[,3:ncol(n)], 1, function(x){sum(x > 0)}) == ncol(n) - 2,]
      if(nrow(cur_n) > 0){
        cur_n$GeneName <- rowData(tissue_sce)$Symbol[match(rownames(cur_n), rowData(tissue_sce)$ID)]
      }
    }
    else{
      cur_n <- NULL
    }
    cur_n
  })
  
  write.xlsx(markers.spec, paste("../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/Marker_genes/Tissues/", i, "/Marker_genes.xlsx", sep = ""))
  
  tissue.list[[i]] <- tissue_sce
}

# Visualize clustering
ggplot(data.frame(tSNE1 = reducedDims(tissue.list$GOJ)$TSNE[,1],
                  tSNE2 = reducedDims(tissue.list$GOJ)$TSNE[,2],
                  clusters = as.factor(colData(tissue.list$GOJ)$Tissue_cluster))) +
  geom_point(aes(tSNE1, tSNE2, colour = clusters))

ggplot(data.frame(tSNE1 = reducedDims(tissue.list$GOJ)$TSNE[,1],
                  tSNE2 = reducedDims(tissue.list$GOJ)$TSNE[,2],
                  clusters = as.factor(colData(tissue.list$GOJ)$Patient))) +
  geom_point(aes(tSNE1, tSNE2, colour = clusters))

saveRDS(tissue.list, "../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Tissue_sce.rds")
```

