---
title: "Figure S7: Cell type proportions in stem cells"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/Figures/Fig_S7.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in the data

```{r libraries, message=FALSE}
library(scran)
library(scater)
library(DropletUtils)
library(openxlsx)
library(Rtsne)
library(pheatmap)
library(cowplot)
library(RColorBrewer)
library(edgeR)
library(ape)
library(viridis)
library(umap)
library(reshape2)
source("../Analysis/Functions/auxiliary.R")
sce <- readRDS("../../../Dropbox (Cambridge University)/Oesophagus_single_cell/All_corrected_sce.rds")
```

# Visualize stem-like cell cluster

Here, we select the cluster that could contain stem-like cells and recluster.

```{r}
# Select cluster 7
cur_sce <- sce[,sce$include & sce$Global_cluster == 7]
cur_sce <- cur_sce[Matrix::rowSums(logcounts(cur_sce)) > 0,]
cur_sce <- normalize(cur_sce)

# Perform batch correction
sce.list <- split.sce(cur_sce, unique(cur_sce$Sample), colData.name = "Sample")
sce.list <- sce.list[c(which(grepl("GOJ", names(sce.list))),
                       which(grepl("SCJ", names(sce.list))),
                       which(grepl("GC", names(sce.list))),
                       which(grepl("BE", names(sce.list))),
                       which(grepl("D2", names(sce.list))),
                       which(grepl("SMG", names(sce.list))))]
corrected <- batch.correction(sce.list)
cur_sce <- do.call("cbind", sce.list)

# Compute the fration of cells per cell type per tissue (GC, BE, D2, SMG)
cur_sce <- cur_sce[,cur_sce$Tissue %in% c("GC", "BE", "D2", "SMG")]

cur_mat <- table(cur_sce$cell_type, cur_sce$Tissue)
cur_mat <- t(t(cur_mat)/colSums(cur_mat))
cur_df <- melt(cur_mat)

# Create colour vector for cell types
colour_vector <- vector(length = nrow(cur_mat))
names(colour_vector) <- rownames(cur_mat)
colour_vector["Chief"] <- colorRampPalette(c("white", "dark blue"))(10)[6]
colour_vector["Dividing"] <- colorRampPalette(c("white", "#3C5488FF"))(10)[3]
colour_vector["Endocrine"] <- colorRampPalette(c("white", "dark blue"))(10)[10]
colour_vector["Enterocytes_Intermediate"] <- colorRampPalette(c("white", "#3C5488FF"))(10)[6]
colour_vector["Foveolar_differentiated"] <- colorRampPalette(c("white", "#3C5488FF"))(10)[10]
colour_vector["Foveolar_Intermediate"] <- colorRampPalette(c("white", "#4DBBD5FF"))(10)[6]
colour_vector["Goblet"] <- colorRampPalette(c("white", "seagreen4"))(10)[10]
colour_vector["Mucous"] <- "saddlebrown"
colour_vector["Paneth"] <- colorRampPalette(c("white", "seagreen4"))(10)[6]
colour_vector["Serous"] <- "burlywood3"
colour_vector["Undifferentiated"] <- colorRampPalette(c("white", "#3C5488FF"))(10)[1]
colour_vector["Duct_intercalating"] <- "burlywood4"

cell_type.barplot <- ggplot(cur_df) +
  geom_col(aes(Var2, value, fill = Var1), colour = "black", lwd = 0.5) + 
  scale_fill_manual(values = colour_vector)

ggsave("../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/Figures/Supplementary_figures/Figure_S7/Cell_type_proportion.pdf", cell_type.barplot, width = 7, height = 5)
```