---
title: "Differential expression in stem cell compartment"
author: "Nils Eling"
date: "10/09/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This script performs differential expression between the stem cells of different tissues.

## Read in the data 

```{r data}
library(scater)
library(scran)
library(edgeR)
library(ggplot2)
library(openxlsx)
library(RColorBrewer)
source("../../Analysis/Functions/auxiliary.R")
sce <- readRDS("../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/All_corrected_sce.rds")
```

# OLFM4 cells

## Select cells

```{r}
# Select all OLFM4 cells
sce_olfm4 <- sce[,logcounts(sce)[rowData(sce)$Symbol == "OLFM4",] > 0]
plot(table(colData(sce_olfm4)$Tissue))
table(colData(sce_olfm4)$Tissue, colData(sce_olfm4)$Patient)
```

## Visualize cells

```{r}
# Tissue
ggplot(data.frame(tSNE1 = reducedDims(sce_olfm4)$TSNE[,1],
                  tSNE2 = reducedDims(sce_olfm4)$TSNE[,2],
                  tissue = colData(sce_olfm4)$Tissue)) +
  geom_point(aes(tSNE1, tSNE2, colour = tissue))

# Patient
ggplot(data.frame(tSNE1 = reducedDims(sce_olfm4)$TSNE[,1],
                  tSNE2 = reducedDims(sce_olfm4)$TSNE[,2],
                  patient = colData(sce_olfm4)$Patient)) +
  geom_point(aes(tSNE1, tSNE2, colour = patient))
```

# D2 vs BE

```{r}
sce.test <- sce_olfm4[,grepl("BE|D2", colData(sce_olfm4)$Tissue)]
sce.test <- sce.test[Matrix::rowMeans(logcounts(sce.test)) > 0.1,]
sce.test <- normalize(sce.test)
  
# Sum counts with each batch and group
mat <- matrix(data = NA, ncol = length(unique(paste(colData(sce.test)$Patient, 
                                        colData(sce.test)$Tissue, sep = "_"))), 
              nrow = nrow(counts(sce.test)))
rownames(mat) <- rownames(counts(sce.test))
colnames(mat) <- unique(paste(colData(sce.test)$Patient, 
                                colData(sce.test)$Tissue, sep = "_"))
  
for(j in colnames(mat)){
  cur_patient <- unlist(strsplit(j, "_"))[1]
  cur_tissue <- unlist(strsplit(j, "_"))[2]
  mat[,j] <- Matrix::rowSums(counts(sce.test)[,colData(sce.test)$Patient == cur_patient &
                                                colData(sce.test)$Tissue == cur_tissue]) 
}
  
# Perform differential testing
y <- DGEList(counts=mat,
             group=sapply(colnames(mat), 
                          function(n){unlist(strsplit(n, "_"))[1]}))
y <- calcNormFactors(y)
design <- model.matrix(~0+sapply(colnames(mat), function(n){unlist(strsplit(n, "_"))[2]}))
colnames(design) <- c("BE", "D2")
y <- estimateDisp(y,design)
  
fit <- glmQLFit(y,design, robust = TRUE)
qlf <- glmTreat(fit,coef=2, lfc = 0.5, 
                contrast = makeContrasts(D2 - BE, levels = design))
cur_markers <- topTags(qlf, n = nrow(qlf$table))$table

# Save markers
cur_out <- list()
cur_out$BE <- cur_markers[cur_markers$logFC < 0 & cur_markers$FDR < 0.01,]
cur_out$BE$Genename <- rowData(sce)$Symbol[match(rownames(cur_out$BE), rowData(sce)$ID)]
cur_out$D2 <- cur_markers[cur_markers$logFC > 0 & cur_markers$FDR < 0.01,]
cur_out$D2$Genename <- rowData(sce)$Symbol[match(rownames(cur_out$D2), rowData(sce)$ID)]

write.xlsx(cur_out, "../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/Marker_genes/DE/OLFM4_cells/BE_vs_D2.xlsx")
```

# Based on clustering

## Visualize clustering

```{r}
ggplot(data.frame(tSNE1 = reducedDims(sce)$TSNE[,1],
                  tSNE2 = reducedDims(sce)$TSNE[,2],
                  cluster = factor(colData(sce)$Tissue_cluster))) +
  geom_point(aes(tSNE1, tSNE2, colour = cluster)) + 
  scale_colour_manual(values = c(brewer.pal(9, "Set1"), 
                                 brewer.pal(8, "Set2"),
                                 brewer.pal(12, "Set3")))

ggplot(data.frame(tSNE1 = reducedDims(sce)$TSNE[,1],
                  tSNE2 = reducedDims(sce)$TSNE[,2],
                  cluster = factor(colData(sce)$Tissue))) +
  geom_point(aes(tSNE1, tSNE2, colour = cluster)) + 
  scale_colour_manual(values = c(brewer.pal(9, "Set1"), 
                                 brewer.pal(8, "Set2"),
                                 brewer.pal(12, "Set3")))

ggplot(data.frame(tSNE1 = reducedDims(sce)$TSNE[,1],
                  tSNE2 = reducedDims(sce)$TSNE[,2],
                  OLFM4 = logcounts(sce)[rowData(sce)$Symbol == "OLFM4",])) +
  geom_point(aes(tSNE1, tSNE2, colour = OLFM4)) + 
  scale_colour_viridis_c()

# Select possible stem cell clusters
sce.sub <- sce[,((colData(sce)$Tissue_cluster == 3 | 
                    colData(sce)$Tissue_cluster == 4) & 
                   colData(sce)$Tissue == "BE") |
                 ((colData(sce)$Tissue_cluster == 3) & 
                   colData(sce)$Tissue == "GC") |
                 (colData(sce)$Tissue_cluster == 4 & 
                   colData(sce)$Tissue == "D2")]

ggplot(data.frame(tSNE1 = reducedDims(sce.sub)$TSNE[,1],
                  tSNE2 = reducedDims(sce.sub)$TSNE[,2],
                  cluster = factor(colData(sce.sub)$Tissue_cluster))) +
  geom_point(aes(tSNE1, tSNE2, colour = cluster)) + 
  scale_colour_manual(values = c(brewer.pal(9, "Set1")))

ggplot(data.frame(tSNE1 = reducedDims(sce.sub)$TSNE[,1],
                  tSNE2 = reducedDims(sce.sub)$TSNE[,2],
                  cluster = factor(colData(sce.sub)$Tissue))) +
  geom_point(aes(tSNE1, tSNE2, colour = cluster)) + 
  scale_colour_manual(values = c(brewer.pal(9, "Set1")))

ggplot(data.frame(tSNE1 = reducedDims(sce.sub)$TSNE[,1],
                  tSNE2 = reducedDims(sce.sub)$TSNE[,2],
                  OLFM4 = logcounts(sce.sub)[rowData(sce.sub)$Symbol == "OLFM4",])) +
  geom_point(aes(tSNE1, tSNE2, colour = OLFM4)) + 
  scale_colour_viridis_c()

table(colData(sce.sub)$Tissue, colData(sce.sub)$Patient)
```

# Differential expression analysis

## GC vs BE

```{r}
sce.test <- sce.sub[,grepl("GC|BE", colData(sce.sub)$Tissue)]
sce.test <- sce.test[Matrix::rowMeans(logcounts(sce.test)) > 0.1,]
sce.test <- normalize(sce.test)
  
# Sum counts with each batch and group
mat <- matrix(data = NA, ncol = length(unique(paste(colData(sce.test)$Patient, 
                                        colData(sce.test)$Tissue, sep = "_"))), 
              nrow = nrow(counts(sce.test)))
rownames(mat) <- rownames(counts(sce.test))
colnames(mat) <- unique(paste(colData(sce.test)$Patient, 
                                colData(sce.test)$Tissue, sep = "_"))
  
for(j in colnames(mat)){
  cur_patient <- unlist(strsplit(j, "_"))[1]
  cur_tissue <- unlist(strsplit(j, "_"))[2]
  mat[,j] <- Matrix::rowSums(counts(sce.test)[,colData(sce.test)$Patient == cur_patient &
                                                colData(sce.test)$Tissue == cur_tissue]) 
}
  
# Perform differential testing
y <- DGEList(counts=mat,
             group=sapply(colnames(mat), 
                          function(n){unlist(strsplit(n, "_"))[1]}))
y <- calcNormFactors(y)
design <- model.matrix(~0+sapply(colnames(mat), function(n){unlist(strsplit(n, "_"))[2]}))
colnames(design) <- c("BE", "GC")
y <- estimateDisp(y,design)
  
fit <- glmQLFit(y,design, robust = TRUE)
qlf <- glmTreat(fit,coef=2, lfc = 0.5, 
                contrast = makeContrasts(GC - BE, levels = design))
cur_markers <- topTags(qlf, n = nrow(qlf$table))$table

# Save markers
cur_out <- list()
cur_out$BE <- cur_markers[cur_markers$logFC < 0 & cur_markers$FDR < 0.01,]
cur_out$BE$Genename <- rowData(sce)$Symbol[match(rownames(cur_out$BE), rowData(sce)$ID)]
cur_out$GC <- cur_markers[cur_markers$logFC > 0 & cur_markers$FDR < 0.01,]
cur_out$GC$Genename <- rowData(sce)$Symbol[match(rownames(cur_out$GC), rowData(sce)$ID)]

write.xlsx(cur_out, "../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/Marker_genes/DE/Cluster_based/BE_vs_GC.xlsx")
```

## BE vs D2

```{r}
sce.test <- sce.sub[,grepl("D2|BE", colData(sce.sub)$Tissue)]
sce.test <- sce.test[Matrix::rowMeans(logcounts(sce.test)) > 0.1,]
sce.test <- normalize(sce.test)
  
# Sum counts with each batch and group
mat <- matrix(data = NA, ncol = length(unique(paste(colData(sce.test)$Patient, 
                                        colData(sce.test)$Tissue, sep = "_"))), 
              nrow = nrow(counts(sce.test)))
rownames(mat) <- rownames(counts(sce.test))
colnames(mat) <- unique(paste(colData(sce.test)$Patient, 
                                colData(sce.test)$Tissue, sep = "_"))
  
for(j in colnames(mat)){
  cur_patient <- unlist(strsplit(j, "_"))[1]
  cur_tissue <- unlist(strsplit(j, "_"))[2]
  mat[,j] <- Matrix::rowSums(counts(sce.test)[,colData(sce.test)$Patient == cur_patient &
                                                colData(sce.test)$Tissue == cur_tissue]) 
}
  
# Perform differential testing
y <- DGEList(counts=mat,
             group=sapply(colnames(mat), 
                          function(n){unlist(strsplit(n, "_"))[1]}))
y <- calcNormFactors(y)
design <- model.matrix(~0+sapply(colnames(mat), function(n){unlist(strsplit(n, "_"))[2]}))
colnames(design) <- c("BE", "D2")
y <- estimateDisp(y,design)
  
fit <- glmQLFit(y,design, robust = TRUE)
qlf <- glmTreat(fit,coef=2, lfc = 0.5, 
                contrast = makeContrasts(D2 - BE, levels = design))
cur_markers <- topTags(qlf, n = nrow(qlf$table))$table

# Save markers
cur_out <- list()
cur_out$BE <- cur_markers[cur_markers$logFC < 0 & cur_markers$FDR < 0.01,]
cur_out$BE$Genename <- rowData(sce)$Symbol[match(rownames(cur_out$BE), rowData(sce)$ID)]
cur_out$D2 <- cur_markers[cur_markers$logFC > 0 & cur_markers$FDR < 0.01,]
cur_out$D2$Genename <- rowData(sce)$Symbol[match(rownames(cur_out$D2), rowData(sce)$ID)]

write.xlsx(cur_out, "../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/Marker_genes/DE/Cluster_based/BE_vs_D2.xlsx")
```

# Differential expression testing Patient 12

```{r patient12}
cur_sce <- sce.sub[,sce.sub$Patient == "Patient12"]
cur_sce <- cur_sce[Matrix::rowMeans(logcounts(cur_sce)) > 0.1,]
cur_sce <- normalise(cur_sce)

markers <- marker.detection(cur_sce, clusters = cur_sce$Tissue)

write.xlsx(markers, "../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/Marker_genes/DE/Patient12/All_markers.xlsx")
```

# DE between SMG and BE

```{r SMG_BE}
# BE C4 vs SMG C5
cur_sce <- sce[,(colData(sce)$Tissue == "BE" & colData(sce)$Tissue_cluster == 4) |
                 (colData(sce)$Tissue == "SMG" & colData(sce)$Tissue_cluster == 5)]
table(colData(cur_sce)$Tissue, colData(cur_sce)$Patient)

cur_sce <- cur_sce[Matrix::rowMeans(logcounts(cur_sce)) > 0.1,]
cur_sce <- normalize(cur_sce)
  
# Sum counts with each batch and group
mat <- matrix(data = NA, ncol = length(unique(paste(colData(cur_sce)$Patient, 
                                        colData(cur_sce)$Tissue, sep = "_"))), 
              nrow = nrow(counts(cur_sce)))
rownames(mat) <- rownames(counts(cur_sce))
colnames(mat) <- unique(paste(colData(cur_sce)$Patient, 
                                colData(cur_sce)$Tissue, sep = "_"))
  
for(j in colnames(mat)){
  cur_patient <- unlist(strsplit(j, "_"))[1]
  cur_tissue <- unlist(strsplit(j, "_"))[2]
  mat[,j] <- Matrix::rowSums(counts(cur_sce)[,colData(cur_sce)$Patient == cur_patient &
                                                colData(cur_sce)$Tissue == cur_tissue]) 
}
  
# Perform differential testing
y <- DGEList(counts=mat,
             group=sapply(colnames(mat), 
                          function(n){unlist(strsplit(n, "_"))[1]}))
y <- calcNormFactors(y)
design <- model.matrix(~0+sapply(colnames(mat), function(n){unlist(strsplit(n, "_"))[2]}))
colnames(design) <- c("BE", "SMG")
y <- estimateDisp(y,design)
  
fit <- glmQLFit(y,design, robust = TRUE)
qlf <- glmTreat(fit,coef=2, lfc = 0.5, 
                contrast = makeContrasts(SMG - BE, levels = design))
cur_markers <- topTags(qlf, n = nrow(qlf$table))$table

# Save markers
cur_out <- list()
cur_out$BE <- cur_markers[cur_markers$logFC < 0 & cur_markers$FDR < 0.01,]
cur_out$BE$Genename <- rowData(sce)$Symbol[match(rownames(cur_out$BE), rowData(sce)$ID)]
cur_out$SMG <- cur_markers[cur_markers$logFC > 0 & cur_markers$FDR < 0.01,]
cur_out$SMG$Genename <- rowData(sce)$Symbol[match(rownames(cur_out$SMG), rowData(sce)$ID)]

write.xlsx(cur_out, "../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/Marker_genes/DE/Cluster_based/BE-C4_vs_SMG-C5.xlsx")

# BE C4 vs SMG C10
cur_sce <- sce[,(colData(sce)$Tissue == "BE" & colData(sce)$Tissue_cluster == 4) |
                 (colData(sce)$Tissue == "SMG" & colData(sce)$Tissue_cluster == 10)]
table(colData(cur_sce)$Tissue, colData(cur_sce)$Patient)

cur_sce <- cur_sce[Matrix::rowMeans(logcounts(cur_sce)) > 0.1,]
cur_sce <- normalize(cur_sce)
  
# Sum counts with each batch and group
mat <- matrix(data = NA, ncol = length(unique(paste(colData(cur_sce)$Patient, 
                                        colData(cur_sce)$Tissue, sep = "_"))), 
              nrow = nrow(counts(cur_sce)))
rownames(mat) <- rownames(counts(cur_sce))
colnames(mat) <- unique(paste(colData(cur_sce)$Patient, 
                                colData(cur_sce)$Tissue, sep = "_"))
  
for(j in colnames(mat)){
  cur_patient <- unlist(strsplit(j, "_"))[1]
  cur_tissue <- unlist(strsplit(j, "_"))[2]
  mat[,j] <- Matrix::rowSums(counts(cur_sce)[,colData(cur_sce)$Patient == cur_patient &
                                                colData(cur_sce)$Tissue == cur_tissue]) 
}
  
# Perform differential testing
y <- DGEList(counts=mat,
             group=sapply(colnames(mat), 
                          function(n){unlist(strsplit(n, "_"))[1]}))
y <- calcNormFactors(y)
design <- model.matrix(~0+sapply(colnames(mat), function(n){unlist(strsplit(n, "_"))[2]}))
colnames(design) <- c("BE", "SMG")
y <- estimateDisp(y,design)
  
fit <- glmQLFit(y,design, robust = TRUE)
qlf <- glmTreat(fit,coef=2, lfc = 0.5, 
                contrast = makeContrasts(SMG - BE, levels = design))
cur_markers <- topTags(qlf, n = nrow(qlf$table))$table

# Save markers
cur_out <- list()
cur_out$BE <- cur_markers[cur_markers$logFC < 0 & cur_markers$FDR < 0.01,]
cur_out$BE$Genename <- rowData(sce)$Symbol[match(rownames(cur_out$BE), rowData(sce)$ID)]
cur_out$SMG <- cur_markers[cur_markers$logFC > 0 & cur_markers$FDR < 0.01,]
cur_out$SMG$Genename <- rowData(sce)$Symbol[match(rownames(cur_out$SMG), rowData(sce)$ID)]

write.xlsx(cur_out, "../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/Marker_genes/DE/Cluster_based/BE-C4_vs_SMG-C10.xlsx")

# BE C4 vs SMG C13
cur_sce <- sce[,(colData(sce)$Tissue == "BE" & colData(sce)$Tissue_cluster == 4) |
                 (colData(sce)$Tissue == "SMG" & colData(sce)$Tissue_cluster == 13)]
table(colData(cur_sce)$Tissue, colData(cur_sce)$Patient)

cur_sce <- cur_sce[Matrix::rowMeans(logcounts(cur_sce)) > 0.1,]
cur_sce <- normalize(cur_sce)
  
# Sum counts with each batch and group
mat <- matrix(data = NA, ncol = length(unique(paste(colData(cur_sce)$Patient, 
                                        colData(cur_sce)$Tissue, sep = "_"))), 
              nrow = nrow(counts(cur_sce)))
rownames(mat) <- rownames(counts(cur_sce))
colnames(mat) <- unique(paste(colData(cur_sce)$Patient, 
                                colData(cur_sce)$Tissue, sep = "_"))
  
for(j in colnames(mat)){
  cur_patient <- unlist(strsplit(j, "_"))[1]
  cur_tissue <- unlist(strsplit(j, "_"))[2]
  mat[,j] <- Matrix::rowSums(counts(cur_sce)[,colData(cur_sce)$Patient == cur_patient &
                                                colData(cur_sce)$Tissue == cur_tissue]) 
}
  
# Perform differential testing
y <- DGEList(counts=mat,
             group=sapply(colnames(mat), 
                          function(n){unlist(strsplit(n, "_"))[1]}))
y <- calcNormFactors(y)
design <- model.matrix(~0+sapply(colnames(mat), function(n){unlist(strsplit(n, "_"))[2]}))
colnames(design) <- c("BE", "SMG")
y <- estimateDisp(y,design)
  
fit <- glmQLFit(y,design, robust = TRUE)
qlf <- glmTreat(fit,coef=2, lfc = 0.5, 
                contrast = makeContrasts(SMG - BE, levels = design))
cur_markers <- topTags(qlf, n = nrow(qlf$table))$table

# Save markers
cur_out <- list()
cur_out$BE <- cur_markers[cur_markers$logFC < 0 & cur_markers$FDR < 0.01,]
cur_out$BE$Genename <- rowData(sce)$Symbol[match(rownames(cur_out$BE), rowData(sce)$ID)]
cur_out$SMG <- cur_markers[cur_markers$logFC > 0 & cur_markers$FDR < 0.01,]
cur_out$SMG$Genename <- rowData(sce)$Symbol[match(rownames(cur_out$SMG), rowData(sce)$ID)]

write.xlsx(cur_out, "../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/Marker_genes/DE/Cluster_based/BE-C4_vs_SMG-C13.xlsx")
```