---
title: "Validation of batch correction"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/Reports/Batch_correction_validation.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in the data

```{r libraries, message=FALSE}
library(scran)
library(scater)
library(DropletUtils)
library(openxlsx)
library(Rtsne)
library(ape)
source("../../Analysis/Functions/auxiliary.R")
```

# Batch correction across tissues

Here, I will use different sets of genes to show that the batch correction is independent from the chosen gene set.

```{r batch-correction}
all_sce <- readRDS("../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/All_corrected_sce.rds")
all_sce <- all_sce[,all_sce$include]
sce.list <- split.sce(sce = all_sce, groups = unique(all_sce$Sample), colData.name = "Sample")

# Combine sce objects
all_sce <- do.call("cbind", sce.list)
  
# Batch correction
corrected_1 <- batch.correction(sce.list, number.HVG = 500)
corrected_2 <- batch.correction(sce.list, number.HVG = 2000)

# Compute tsne on corrected counts
set.seed(1234)
tsne_1 <- Rtsne(t(corrected_1), pca = FALSE)
tsne_2 <- Rtsne(t(corrected_2), pca = FALSE)

p.tsne.500 <- ggplot(data.frame(tSNE1 = tsne_1$Y[,1],
                  tSNE2 = tsne_1$Y[,2],
                  clusters = as.factor(colData(all_sce)$Tissue))) + 
  geom_point(aes(tSNE1, tSNE2, colour = clusters)) +
  scale_colour_manual(values = metadata(all_sce)$colour_vector)
ggsave("../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/BatchCorrectionValidation/tsne_500HVG.pdf", 
       p.tsne.500, width = 12, height = 7)

p.tsne.2000 <- ggplot(data.frame(tSNE1 = tsne_2$Y[,1],
                  tSNE2 = tsne_2$Y[,2],
                  clusters = as.factor(colData(all_sce)$Tissue))) + 
  geom_point(aes(tSNE1, tSNE2, colour = clusters)) +
  scale_colour_manual(values = metadata(all_sce)$colour_vector)
ggsave("../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/BatchCorrectionValidation/tsne_2000HVG.pdf", 
       p.tsne.2000, width = 12, height = 7)

# dendogram analysis
clusters <- paste(colData(all_sce)$Tissue, colData(all_sce)$Tissue_cluster, sep = "_")
mat_1 <- mat_2 <- matrix(data = NA, ncol = length(unique(clusters)), nrow = nrow(corrected_1))
colnames(mat_1) <- colnames(mat_2) <- unique(clusters)

for(i in unique(clusters)){
  mat_1[,i] <- rowMeans(corrected_1[,clusters == i])
  mat_2[,i] <- rowMeans(corrected_2[,clusters == i])
}

# Rename the matrix to contain the actual cell-type labels
for(i in 1:ncol(mat_1)){
  colnames(mat_1)[i] <- unique(all_sce$cell_type[all_sce$Tissue == sub("_[0-9]*$", "", colnames(mat_1)[i]) &
                                 all_sce$Tissue_cluster == sub("^[A-Z2]*_", "", colnames(mat_1)[i])])
  colnames(mat_2)[i] <- unique(all_sce$cell_type[all_sce$Tissue == sub("_[0-9]*$", "", colnames(mat_2)[i]) &
                                 all_sce$Tissue_cluster == sub("^[A-Z2]*_", "", colnames(mat_2)[i])])
}

# Calculate euclidean distance on corrected counts
dend_1 <- hclust(dist(t(mat_1), method = "euclidean"), method = "ward.D2")
dend_2 <- hclust(dist(t(mat_2), method = "euclidean"), method = "ward.D2")
pdf("../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/BatchCorrectionValidation/Tree_500HVG.pdf", width = 10, height = 10)
plot(as.phylo(dend_1), type = "fan", 
     tip.color = metadata(all_sce)$colour_vector[sub("_[0-9]*$", "", unique(clusters))])
dev.off()
pdf("../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/BatchCorrectionValidation/Tree_2000HVG.pdf", width = 10, height = 10)
plot(as.phylo(dend_2), type = "fan", 
     tip.color = metadata(all_sce)$colour_vector[sub("_[0-9]*$", "", unique(clusters))])
dev.off()
```

Next, I will use scanorama and Seurat to perform the same mapping strategy.

```{r}


```