---
title: "Comparison of Teichmann and Fitzgerald data"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, 
        encoding = encoding, output_file = '../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Results/Reports/Teichmann_Fitzgerald_comparison.html') })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This script compares data generated by the Teichmann lab versus data generated by the Fitzgerald lab.
I will start with raw counts and select the conditions of interest.
For convenience, the analysis is performed using `scran`.

The first step is to select oesophagus cells from the Teichmann lab at 0-6 hours after sampling.

## Select condition of interest

```{r, select-condition}
library(scran)
library(Seurat)

# Read in the Teichmann data
T.data <- readRDS("../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Teichman_data/Data/Oesophagus_QC_TSNE_alldonors.gz")

# Strip out the data that we don't need for easier handeling
T.data@data <- NULL
T.data@scale.data <- NULL
saveRDS(T.data, "../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/Teichman_data/Data/Teichmann_data_small.rds")
```