---
title: "Trajectory analysis"
author: "Nils Eling"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This script performs trajectory analysis on the BE and GC samples

## Read in batch corrected data

```{r}
library(scran)
library(Rtsne)
library(ggplot2)
library(viridis)
library(monocle)
library(plot3Drgl)
sce <- readRDS("../../../../Dropbox (Cambridge University)/Oesophagus_single_cell/All_corrected_sce.rds")

# Select only GC and BE
corrected <- metadata(sce)$corrected[,colData(sce)$Tissue == "BE" | colData(sce)$Tissue == "GC"]
sce <- sce[,colData(sce)$Tissue == "BE" | colData(sce)$Tissue == "GC"]
colnames(corrected) <- paste(colData(sce)$Barcode, colData(sce)$Patient, colData(sce)$Tissue, sep = "_")
```

# Try different visualization techniques

## PCA

```{r}
# Batch corrected data already come as pca
ggplot(data.frame(PC1 = corrected[1,],
                  PC2 = corrected[2,],
                  tissue = colData(sce)$Tissue,
                  patient = colData(sce)$Patient)) + 
  geom_point(aes(x = PC1, y = PC2, colour = tissue))

ggplot(data.frame(PC1 = corrected[1,],
                  PC2 = corrected[2,],
                  tissue = colData(sce)$Tissue,
                  patient = colData(sce)$Patient)) + 
  geom_point(aes(x = PC1, y = PC2, colour = patient))

# Visualize OLFM4
ggplot(data.frame(PC1 = corrected[1,],
                  PC2 = corrected[2,],
                  OLFM4 = logcounts(sce)[rowData(sce)$Symbol == "OLFM4",])) +
  geom_point(aes(x = PC1, y = PC2, colour = OLFM4)) + scale_colour_viridis()


# Remove outlying cells
sce <- sce[,corrected[1,] > -0.1]
corrected <- corrected[,corrected[1,] > -0.1]

ggplot(data.frame(PC1 = corrected[1,],
                  PC2 = corrected[2,],
                  tissue = colData(sce)$Tissue,
                  patient = colData(sce)$Patient)) + 
  geom_point(aes(x = PC1, y = PC2, colour = tissue))

ggplot(data.frame(PC1 = corrected[1,],
                  PC2 = corrected[2,],
                  OLFM4 = logcounts(sce)[rowData(sce)$Symbol == "OLFM4",])) +
  geom_point(aes(x = PC1, y = PC2, colour = OLFM4)) + scale_colour_viridis()

ggplot(data.frame(PC1 = corrected[2,],
                  PC2 = corrected[3,],
                  tissue = colData(sce)$Tissue,
                  patient = colData(sce)$Patient)) + 
  geom_point(aes(x = PC1, y = PC2, colour = tissue))

ggplot(data.frame(PC1 = corrected[2,],
                  PC2 = corrected[3,],
                  OLFM4 = logcounts(sce)[rowData(sce)$Symbol == "OLFM4",])) +
  geom_point(aes(x = PC1, y = PC2, colour = OLFM4)) + scale_colour_viridis()

ggplot(data.frame(PC1 = corrected[3,],
                  PC2 = corrected[4,],
                  tissue = colData(sce)$Tissue,
                  patient = colData(sce)$Patient)) + 
  geom_point(aes(x = PC1, y = PC2, colour = tissue))

ggplot(data.frame(PC1 = corrected[3,],
                  PC2 = corrected[4,],
                  OLFM4 = logcounts(sce)[rowData(sce)$Symbol == "OLFM4",])) +
  geom_point(aes(x = PC1, y = PC2, colour = OLFM4)) + scale_colour_viridis()
```

PCA does not resolve the substructure

## tSNE

```{r}
set.seed(12345)
tsne <- Rtsne(t(corrected), pca = FALSE)

ggplot(data.frame(tsne1 = tsne$Y[,1],
                  tsne2 = tsne$Y[,2],
                  tissue = colData(sce)$Tissue,
                  patient = colData(sce)$Patient)) + 
  geom_point(aes(x = tsne1, y = tsne2, colour = tissue))

ggplot(data.frame(tsne1 = tsne$Y[,1],
                  tsne2 = tsne$Y[,2],
                  OLFM4 = logcounts(sce)[rowData(sce)$Symbol == "OLFM4",])) +
  geom_point(aes(x = tsne1, y = tsne2, colour = OLFM4)) + scale_colour_viridis()

```


## Monocle

```{r}
# Build monocle object
cur_pd <- as.data.frame(colData(sce))
rownames(cur_pd) <- colnames(corrected)
pd <- new("AnnotatedDataFrame", data = cur_pd)
#fd <- new("AnnotatedDataFrame", data = data.frame(gene_short_name = paste("PC", 1:50, sep = "")))
cds <- newCellDataSet(corrected, phenoData = pd)

# cluster cells
cds <- clusterCells(cds)

cds <- estimateSizeFactors(cds)
cds <- reduceDimension(cds, max_components = 2,
    method = 'DDRTree')
cds <- orderCells(cds)

plot_cell_trajectory(cds, color_by = "Tissue")

ggplot(data.frame(tsne1 = cds@reducedDimS[1,],
                  tsne2 = cds@reducedDimS[2,],
                  OLFM4 = logcounts(sce)[rowData(sce)$Symbol == "OLFM4",])) +
  geom_point(aes(x = tsne1, y = tsne2, colour = OLFM4)) + scale_colour_viridis()
```











```{r}
# Number of OLFM4 expressing cells in GC and BE
length(which(logcounts(sce)[rowData(sce)$Symbol == "OLFM4",
                            colData(sce)$Tissue == "GC"] > 0))
length(which(logcounts(sce)[rowData(sce)$Symbol == "OLFM4",
                            colData(sce)$Tissue == "BE"] > 0))

# Only visualize the OLFM4 positive cells
tsne_red <- tsne$Y[logcounts(sce)[rowData(sce)$Symbol == "OLFM4",] > 0,]
sce_red <- sce[,logcounts(sce)[rowData(sce)$Symbol == "OLFM4",] > 0]

ggplot(data.frame(tsne1 = tsne_red[,1],
                  tsne2 = tsne_red[,2],
                  tissue = colData(sce_red)$Tissue,
                  patient = colData(sce_red)$Patient)) + 
  geom_point(aes(x = tsne1, y = tsne2, colour = tissue))
```